### ISSUE TITLE
Dijkstra’s shortest path algorithm in C++

### ISSUE THREAD

**Issue by vishal1patidar** [puruagarwal1/hacktoberfest-2022-directory#36]
I would like to contribute Dijkstra’s shortest path algorithm in C++,  Please assign this issue to me @puruagarwal1 Under hacktoberfest 2022

**Comment by puruagarwal1** [comment]
give star on the upper right corner of my repo.

**Comment by vishal1patidar** [comment]
Review my pull request and merge it 
Thank you
