### ISSUE TITLE
Quick Sort Algorithm using Java

### ISSUE THREAD

**Issue by LiQuiD-404** [puruagarwal1/hacktoberfest-2022-directory#57]
**Is your feature request related to a problem? Please describe.**
Quick Sort is one of the most efficient sorting algorithms used to sort an array of numbers. The time complexity of this type of sorting algorithm is O(N log N) which makes is extremely efficient.

**Describe the solution you'd like**
I would like to implement Quick Sort using Java.

I will be working on this issue under Hacktoberfest'22.

**Comment by puruagarwal1** [comment]
give star on the upper right corner of my repo.
