### ISSUE TITLE
Reversing a Linked List

### ISSUE THREAD

**Issue by nabeel001** [puruagarwal1/hacktoberfest-2022-directory#61]
I want to contribute the solution to reversing a Linked list in C++. Please assign this issue to me @puruagarwal1

**Comment by Atharva-D** [comment]
I would love to contribute by giving a solution for reversing a Linked List in C++, python, and Java. Please assign this issue to me.

**Comment by puruagarwal1** [comment]
give star on the upper right corner of my repo.

**Comment by amanfangeria980** [comment]
can i also contribute to this?

**Comment by Atharva-D** [comment]
I have added the solutions in c++, java, and python. Please review them and merge my request.

**Comment by puruagarwal1** [comment]
okk will do
