### ISSUE TITLE
Implementing Tree Traversals using C

### ISSUE THREAD

**Issue by LiQuiD-404** [puruagarwal1/hacktoberfest-2022-directory#64]
**Is your feature request related to a problem? Please describe.**
A binary tree can be traversed in inorder, preorder and postorder.

**Describe the solution you'd like**
I would like to implement a program which can traverse a binary tree in inorder, preorder and postorder.

I will be working on this under Hacktoberfest'22.

**Comment by Atharva-D** [comment]
I want to contribute to this issue by providing solutions for preorder, inorder, postorder, BFS, and DFS in C++. Please assign this issue to me @puruagarwal1

**Comment by puruagarwal1** [comment]
give star on the upper right corner of my repo.

**Comment by puruagarwal1** [comment]
done assigned

**Comment by LiQuiD-404** [comment]
> I want to contribute to this issue by providing solutions for preorder, inorder, postorder, BFS, and DFS in C++. Please assign this issue to me @puruagarwal1

Since I am working on Tree Traversals. You can make an issue to implement BFS and DFS.
