### ISSUE TITLE
Add implementation of Quick and Merge Sort in C++ 

### ISSUE THREAD

**Issue by Prajwal0225** [puruagarwal1/hacktoberfest-2022-directory#82]
I would love to add the Implementation of Quick and Merge Sort in C++ in this repo.

@puruagarwal1 can you assign this issue to me?

**Comment by Atharva-D** [comment]
I would really like to contribute the Quick and Merge Sort Implementation in C++ to this repository. @puruagarwal1 Could you please assign me this issue

**Comment by imNilabja** [comment]
I would like to do this task,can you assign me.
